services:
  app:
    build:
      context: .
      x-bake:
        tags:
          - ghcr.io/${GITHUB_REPOSITORY}:latest
          - ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_SHA}
        platforms:
          - linux/amd64
          - linux/arm64
    ports:
      - "3002:3002"
    env_file:
      - .env
    volumes:
      - ./public/script.json:/app/public/script.json
      - ./public/treatment.txt:/app/public/treatment.txt
